### PR TITLE
Ported everything to TypeScript

### PR DESCRIPTION
**Pull request by s2lsoftener**
I haven't tested yet whether the bot will run stably, or if all the commands still work.

### CODE REVIEW

**Comment by NostalgiaNinja** [comment]
I'll see what you've got so far, thanks.

**Review by NostalgiaNinja — DISMISSED** [review]
As discussed on Discord, please make changes to name, alias command fixes.

**Review by NostalgiaNinja — COMMENTED** [review]
.gitignore - `src/data/database.sqlite`
Databases (and other sensitive information held in config.json) should not be stored on repositories.

{$prefix}ver removed.  Version handling will probably be added later on.

I'll see if I can submit a patch to this PR so that the missing commands and the command subsets are all set up correctly, but the core for the bot looks a lot better.  Should we propose moving from json to dotenv?  Would remove once more instance of using fs.

**Comment by s2lsoftener** [comment]
We can keep the convenience of the json structure by trying out the dotenv-json package https://www.npmjs.com/package/dotenv-json

Then in the files it would be (I think):

```javascript
import dotenvJson from 'dotenv-json';
dotenvJson();
```

**Comment by NostalgiaNinja** [comment]
[commands.zip](https://github.com/NostalgiaNinja/Puyobot/files/3350476/commands.zip)

Modified commands - looks good so far.  Please verify if these are correct and then I'll resolve/squash/force push

**Pull request merged**
